DROP table IF EXISTS configurations;
DROP table IF EXISTS game_boards;
DROP table IF EXISTS game_boards_history;
DROP table IF EXISTS sessions;

create table IF NOT EXISTS  configurations (
  id bigint not null generated by default as identity,
  game_session varchar(36) not null,
  number_of_stones int default 0,
  step_back_allowed tinyint default 0,
  auto_rotate tinyint default 0,
  alias1 varchar(120) default 'Player 1',
  alias2 varchar(120) default 'Player 2',
  created_on timestamp default current_timestamp,
  updated_on timestamp default current_timestamp,
  primary key (id)
);

create table IF NOT EXISTS game_boards (
  id bigint not null generated by default as identity,
  game_session varchar(36) not null,
  p1_01 int not null default 0,
  p1_02 int not null default 0,
  p1_03 int not null default 0,
  p1_04 int not null default 0,
  p1_05 int not null default 0,
  p1_06 int not null default 0,
  p1_total int not null default 0,
  p2_01 int not null default 0,
  p2_02 int not null default 0,
  p2_03 int not null default 0,
  p2_04 int not null default 0,
  p2_05 int not null default 0,
  p2_06 int not null default 0,
  p2_total int not null default 0,
  player_to_move_next tinyint default null,
  winner tinyint default 0,
  created_on timestamp not null default current_timestamp,
  updated_on timestamp default null,
  primary key (id),
  constraint game_boards_uid_001
    unique (game_session)
);

create table IF NOT EXISTS game_boards_history (
  id bigint not null generated by default as identity,
  game_session varchar(36) not null,
  p1_01 int not null default 0,
  p1_02 int not null default 0,
  p1_03 int not null default 0,
  p1_04 int not null default 0,
  p1_05 int not null default 0,
  p1_06 int not null default 0,
  p1_total int not null default 0,
  p2_01 int not null default 0,
  p2_02 int not null default 0,
  p2_03 int not null default 0,
  p2_04 int not null default 0,
  p2_05 int not null default 0,
  p2_06 int not null default 0,
  p2_total int not null default 0,
  player_to_move_next tinyint default null,
  winner tinyint default 0,
  created_on timestamp not null default current_timestamp,
  primary key (id)
);

create table IF NOT EXISTS sessions (
  id int not null generated by default as identity,
  session_id varchar(36) not null,
  created_on timestamp not null default current_timestamp,
  updated_on timestamp default current_timestamp,
  primary key (id),
  constraint session_id_UNIQUE
    unique (session_id)
);